#ifndef EXAMPLES_HOST_CONTEXT_REACTO_FACTORY_CONFIG_H_
#define EXAMPLES_HOST_CONTEXT_REACTO_FACTORY_CONFIG_H_

#define REACTO_N_OF_QUEUES 2
#define REACTO_MAX_N_OF_HANDLERS_PER_QUEUE 1

#endif /* EXAMPLES_HOST_CONTEXT_REACTO_FACTORY_CONFIG_H_ */
