coverage:
  ignore:
    - "/usr"
    - "dependencies/*"
    - "*/UtestPlatform.cpp"

comment:
  layout: "header, diff, tree"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  branches: null
  flags: null
  paths: null
