#!python
Import('env')

r = {
    'libs' : [],
    'path' : []
}
r['path'].append(Dir('./'))

src = env.FindFiles('./', '*.c')
Depends(env.SourceToObjects(src), env['CPPINCLUDES'])

lib = env.StaticLibrary('lpc_board', src)
r['libs'].append(lib)
Return('r')
