#!python
Import('env')

penv = env.Clone()
penv.Append(CPPPATH=['./'])

r = {
    'libs' : [],
    'path' : []
}
r['path'].append(Dir('./'))

src = Glob('./*/*.c')
lib = penv.StaticLibrary('qf_demo', src)

objs = [File('#' + s.path.replace('.cpp', '.o').replace('.c', '.o')) for s in src]
for obj in objs:
    Depends(obj, env['CPPINCLUDES'])

r['libs'].append(lib)
Return('r')
