#!python
Import('env')

penv = env.Clone()
penv.Append(CPPPATH=['./'])

r = {
    'libs' : [],
    'path' : []
}
r['path'].append(Dir('./'))

src = Glob('./*/*.c')
lib = penv.StaticLibrary('pq_projeto', src)

Depends ('./*/*.o', env['O_DEPS'])

r['libs'].append(lib)
Return('r')
