#!python

Import('platforms')

for name, plat in platforms.items():
    env = plat['env'].Clone()
    build_dir = './build/' + name
    exe = env.SConscript('./Sconscript.variant', exports = ['name','env'], variant_dir = build_dir, src = 'tests', duplicate=0)

    # Add build results symbols to the platform
    plat['msp430_blink_build_dir'] = Dir(build_dir)
    plat['msp430_blink_executable'] = exe['exe']
    plat['msp430_blink_map_file'] = exe['map']
