#!python
Import('env')

r = {
    'libs' : [],
    'path' : []
}
r['path'].append(Dir('./'))

src = env.FindFiles('./', '*.c')
Depends(env.SourceToObjects(src), env['CPPINCLUDES'])

lib_cmsis = env.StaticLibrary('cmsisv2p00', src)
r['libs'].append(lib_cmsis)
Return('r')
