#!python

Import('platforms')

for plat in platforms:
    name = plat.Name()
    env = plat.Env().Clone()
    env.UpdateIncludes()
    build_dir = './build/' + name
    exe = env.SConscript('./Sconscript.variant', exports = ['name','env'], variant_dir = build_dir, src = 'tests', duplicate=0)

    # Add build results symbols to the platform
    plat.BuildListAddDirectory('msp430_timed_blink', Dir(build_dir))
    plat.BuildListAddBinary('msp430_timed_blink', exe['exe'])
    # plat['msp430_timed_blink_map_file'] = exe['map']
