#!python

Import('platforms')

for plat in platforms:
    name = plat.Name()
    env = plat.Env().Clone()
    build_dir = './build/' + name
    exe = env.SConscript('./src/Sconscript.variant', exports = ['name','env'], variant_dir = build_dir, src = 'src', duplicate=0)

    # Add build results symbols to the platform
    plat.BuildListAddDirectory('host_factory', Dir(build_dir))
    plat.BuildListAddBinary('host_factory', exe['exe'])
    # plat['host_factory_map_file'] = exe['map']
